import type { CoreTheme } from "../theme/themeRegistry";

export const THEME_COLOR_NAMES = [
  "background",
  "background-muted",
  "foreground",
  "sidebar",
  "muted",
  "muted-foreground",
  "muted-border",
  "card",
  "card-foreground",
  "card-hover",
  "popover",
  "popover-foreground",
  "border",
  "input",
  "switch",
  "primary",
  "primary-foreground",
  "primary-border",
  "primary-hover",
  "secondary",
  "secondary-border",
  "secondary-foreground",
  "secondary-hover",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "destructive-border",
  "destructive-hover",
  "primary-cta",
  "primary-cta-foreground",
  "primary-cta-border",
  "primary-cta-hover",
  "ring",
  "link",
  "link-hover",
  "skeleton",
  "code",
  "chart-1-primary",
  "chart-2-primary",
  "chart-3-primary",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "chart-6",
  "chart-7",
  "chart-8",
  "detail-success",
  "detail-failure",
  "detail-warning",
  "detail-neutral",
  "detail-brand",
] as const;

export type ThemeColorName = (typeof THEME_COLOR_NAMES)[number];

export function getThemeColor(
  _resolvedTheme: CoreTheme,
  themeColorName: ThemeColorName,
) {
  return `rgb(var(--${themeColorName}))`;
}
