/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsOverlaysRouteImport } from './routes/components.overlays'
import { Route as ComponentsNavigationRouteImport } from './routes/components.navigation'
import { Route as ComponentsInputsRouteImport } from './routes/components.inputs'
import { Route as ComponentsFoundationsRouteImport } from './routes/components.foundations'
import { Route as ComponentsCustomRouteImport } from './routes/components.custom'

const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsOverlaysRoute = ComponentsOverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsNavigationRoute = ComponentsNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsInputsRoute = ComponentsInputsRouteImport.update({
  id: '/inputs',
  path: '/inputs',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsFoundationsRoute = ComponentsFoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsCustomRoute = ComponentsCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => ComponentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/components': typeof ComponentsRouteWithChildren
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/traces': typeof TracesRoute
  '/components/custom': typeof ComponentsCustomRoute
  '/components/foundations': typeof ComponentsFoundationsRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components/navigation': typeof ComponentsNavigationRoute
  '/components/overlays': typeof ComponentsOverlaysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/components': typeof ComponentsRouteWithChildren
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/traces': typeof TracesRoute
  '/components/custom': typeof ComponentsCustomRoute
  '/components/foundations': typeof ComponentsFoundationsRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components/navigation': typeof ComponentsNavigationRoute
  '/components/overlays': typeof ComponentsOverlaysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/components': typeof ComponentsRouteWithChildren
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/traces': typeof TracesRoute
  '/components/custom': typeof ComponentsCustomRoute
  '/components/foundations': typeof ComponentsFoundationsRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components/navigation': typeof ComponentsNavigationRoute
  '/components/overlays': typeof ComponentsOverlaysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/components'
    | '/sessions'
    | '/settings'
    | '/traces'
    | '/components/custom'
    | '/components/foundations'
    | '/components/inputs'
    | '/components/navigation'
    | '/components/overlays'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/components'
    | '/sessions'
    | '/settings'
    | '/traces'
    | '/components/custom'
    | '/components/foundations'
    | '/components/inputs'
    | '/components/navigation'
    | '/components/overlays'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/components'
    | '/sessions'
    | '/settings'
    | '/traces'
    | '/components/custom'
    | '/components/foundations'
    | '/components/inputs'
    | '/components/navigation'
    | '/components/overlays'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  TracesRoute: typeof TracesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/overlays': {
      id: '/components/overlays'
      path: '/overlays'
      fullPath: '/components/overlays'
      preLoaderRoute: typeof ComponentsOverlaysRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/navigation': {
      id: '/components/navigation'
      path: '/navigation'
      fullPath: '/components/navigation'
      preLoaderRoute: typeof ComponentsNavigationRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/inputs': {
      id: '/components/inputs'
      path: '/inputs'
      fullPath: '/components/inputs'
      preLoaderRoute: typeof ComponentsInputsRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/foundations': {
      id: '/components/foundations'
      path: '/foundations'
      fullPath: '/components/foundations'
      preLoaderRoute: typeof ComponentsFoundationsRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/custom': {
      id: '/components/custom'
      path: '/custom'
      fullPath: '/components/custom'
      preLoaderRoute: typeof ComponentsCustomRouteImport
      parentRoute: typeof ComponentsRoute
    }
  }
}

interface ComponentsRouteChildren {
  ComponentsCustomRoute: typeof ComponentsCustomRoute
  ComponentsFoundationsRoute: typeof ComponentsFoundationsRoute
  ComponentsInputsRoute: typeof ComponentsInputsRoute
  ComponentsNavigationRoute: typeof ComponentsNavigationRoute
  ComponentsOverlaysRoute: typeof ComponentsOverlaysRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsCustomRoute: ComponentsCustomRoute,
  ComponentsFoundationsRoute: ComponentsFoundationsRoute,
  ComponentsInputsRoute: ComponentsInputsRoute,
  ComponentsNavigationRoute: ComponentsNavigationRoute,
  ComponentsOverlaysRoute: ComponentsOverlaysRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  TracesRoute: TracesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
